### ISSUE TITLE
Recurse index

### ISSUE THREAD

**Issue by bottleling** [Zelazny7/isofor#1]
Hi, Thanks for your code. 
I believe `recurse` should be take `idx[which(f)]` instead of just `which(f)`. Otherwise, the `split_on_var` will use the wrong rows and partition elements which might already have been partitioned. Try it.

This is with the original library:
![image](https://cloud.githubusercontent.com/assets/5437360/20920843/85efd14c-bbdc-11e6-88d1-d21af9bf33a3.png)
It immediately doesn't make sense because how can you further partition JAPAN, SINGAPORE into LONDON?

After editing the following, rebuild and reload:
```
recurse <- function(idx, e, l, ni=0, env) {
   ....
  ## recurse
  recurse(idx[which(f)] , e + 1, l, nL, env)
  recurse(idx[which(!f)], e + 1, l, nR, env)
}
```

Then run
```
get_split_factor<-function(x,v){
  l = which(levels(x) %in% unique(x))
  i = l[which(intToBits(v) == 1)]
  list(i=i,filter = levels(x)[i])
}

get_df_from_tree<-function(tree){
  df<-as.data.frame(tree)
  df$NodeNumber<-as.numeric(rownames(df))
  df$NodeName <- sapply(1:nrow(df), function(x) {
    i = df$SplitAtt[x]
    if (i!=0) { mod$vNames[i] }
    else {  paste0(df$Size[x])  }
  } )
  return(df)
}

set.seed(101)
mydata<-data.frame(Height=rnorm(10,1.5,0.4), Weight=c(rep(50,5), rep(45,5)), Region=c(rep(c("JAPAN","SINGAPORE","LONDON"),3), "SINGAPORE"))
mydata$Region<-as.factor(mydata$Region)
set.seed(101)
mod<-iForest(mydata,1,10)
df<-get_df_from_tree(mod$forest[[1]])
adjm <- t( sapply(1:nrow(df), function(x) {
  v <- rep(0, nrow(df))
  if (df$Left[x]!=0) {
    v[df$Left[x]] = 1
    v[df$Right[x]] = 1
  }
  return(v) }
) )

g<- igraph::graph_from_adjacency_matrix(adjm)
plot(g, layout=layout_as_tree(g),vertex.size=4, vertex.label=df$NodeName, edge.arrow.mode="-", edge.label=
       na.omit( unlist(sapply(1:nrow(df), function(x) {
         if(sum(adjm[x,])>0) {
           if(df$AttType[x] == 2) return(c ( paste0(get_split_factor(mydata[,df$SplitAtt[x]], df$SplitValue[x])$filter,collapse=","),"" ) )
           return(c(paste0("<",round(df$SplitValue[x],2)) ,""))
          }
         return(NA) } ) ) ) )

```
![image](https://cloud.githubusercontent.com/assets/5437360/20920762/318f6888-bbdc-11e6-9990-fad39502ca3a.png)

**Comment by gravesee** [comment]
Hi, thanks for catching this! Oddly enough the performance didn't drop much. The distribution looked a lot different though. After your fix it's back to before

**Comment by gravesee** [comment]
btw, do you mind if I incorporate some of your igraph code into the package? I started working on some visualization capabilities.

**Comment by bottleling** [comment]
Sure,  thank you :):)
