### ISSUE TITLE
Having a hard time installing the tool

### ISSUE THREAD

**Issue by BenMachineLearning** [Zelazny7/isofor#4]
Hi,

I'm trying to install but I get the following message "Error: Could not find build tools necessary to build isofor". Before that the downloader asked me if I wanted to install other tools required. Is it normal ? Is there a manual way please ?

Thanks a lot !

**Comment by gravesee** [comment]
Hi, you need to install Rtools in order to install packages from source. Sorry if that wasn't clear. You can use this function from the `installr` package: `installr::install.Rtools()`
